services:
  yt-monitor:
    build: .
    container_name: yt_monitor_bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      - /home/daniel/obsidian:/app/obsidian
