import markdown
from weasyprint import HTML
import os

class PDFGenerator:
    def generate(self, md_content, output_path):
        """
        Converts Markdown content to a PDF file.
        """
        # Convert Markdown to HTML
        html_content = markdown.markdown(md_content, extensions=['extra', 'smarty'])
        
        # Add some basic styling
        styled_html = f"""
        <html>
        <head>
            <style>
                @page {{
                    margin: 1.5cm;
                    @bottom-right {{
                        content: "Page " counter(page) " of " counter(pages);
                        font-size: 9pt;
                        color: #777;
                    }}
                }}
                body {{ 
                    font-family: 'Segoe UI', 'Helvetica', 'Arial', sans-serif; 
                    line-height: 1.6; 
                    color: #2c3e50; 
                }}
                h1 {{ 
                    color: #2c3e50; 
                    font-size: 24pt;
                    border-bottom: 3px solid #3498db; 
                    padding-bottom: 10px; 
                    margin-top: 0;
                }}
                a {{
                    color: #3498db;
                    text-decoration: none;
                }}
                a:hover {{
                    text-decoration: underline;
                }}
                h2 {{ 
                    color: #2980b9; 
                    font-size: 18pt;
                    margin-top: 25px; 
                    border-bottom: 1px solid #eee; 
                    padding-bottom: 5px;
                }}
                h3 {{
                    color: #34495e;
                    font-size: 14pt;
                    margin-top: 20px;
                }}
                /* Metadata block styling */
                h2:first-of-type + ul {{
                    background-color: #f8f9fa;
                    padding: 15px 15px 15px 35px;
                    border-left: 5px solid #3498db;
                    border-radius: 4px;
                    list-style-type: none;
                    margin-bottom: 25px;
                }}
                h2:first-of-type + ul li {{
                    margin-bottom: 8px;
                    font-size: 11pt;
                }}
                h2:first-of-type + ul li strong {{
                    color: #2980b9;
                    display: inline-block;
                    width: 120px;
                }}
                
                ul {{ margin-bottom: 15px; }}
                li {{ margin-bottom: 8px; }}
                
                blockquote {{ 
                    font-style: italic; 
                    color: #7f8c8d; 
                    border-left: 4px solid #bdc3c7; 
                    padding-left: 20px; 
                    margin: 20px 0;
                }}
                p {{ margin-bottom: 15px; text-align: justify; }}
                
                .footer {{
                    position: fixed;
                    bottom: 0;
                    width: 100%;
                    text-align: center;
                    font-size: 8pt;
                    color: #bdc3c7;
                    border-top: 1px solid #eee;
                    padding-top: 5px;
                }}
            </style>
        </head>
        <body>
            {html_content}
            <div class="footer">
                Generated by YouTube Monitor - Internal Report
            </div>
        </body>
        </html>
        """
        
        # Generate PDF
        HTML(string=styled_html).write_pdf(output_path)
        return output_path

if __name__ == "__main__":
    # Test stub
    gen = PDFGenerator()
    test_md = """
# Test Summary
## Narrative Summary
This is a test summary. It should look nice in a PDF.
Second paragraph of the narrative.
## Key Points
- Point 1
- Point 2
## Notable Quotes
- "Hello world" (00:01)
    """
    gen.generate(test_md, "test_summary.pdf")
    print("Generated test_summary.pdf")
